// Source de verite unique du contenu du quiz.
//
// Fichier genere par tools/extract-data.py depuis mendel-ios/Mendel-iOS/
// QuizModel.swift -- ne pas editer a la main. C'etait la version Android
// (QuizGenerator.kt) qui portait aussi ces listes, en plus court et avec
// sept ions commentes; cette version-ci fait autorite.
//
// 62 elements, 20 ions polyatomiques, 79 phrases de retour.

export const ELEMENTS = [
  { z: 1, symbol: 'H', name: 'Hydrogène' },
  { z: 2, symbol: 'He', name: 'Hélium' },
  { z: 3, symbol: 'Li', name: 'Lithium' },
  { z: 4, symbol: 'Be', name: 'Béryllium' },
  { z: 5, symbol: 'B', name: 'Bore' },
  { z: 6, symbol: 'C', name: 'Carbone' },
  { z: 7, symbol: 'N', name: 'Azote' },
  { z: 8, symbol: 'O', name: 'Oxygène' },
  { z: 9, symbol: 'F', name: 'Fluor' },
  { z: 10, symbol: 'Ne', name: 'Néon' },
  { z: 11, symbol: 'Na', name: 'Sodium' },
  { z: 12, symbol: 'Mg', name: 'Magnésium' },
  { z: 13, symbol: 'Al', name: 'Aluminium' },
  { z: 14, symbol: 'Si', name: 'Silicium' },
  { z: 15, symbol: 'P', name: 'Phosphore' },
  { z: 16, symbol: 'S', name: 'Soufre' },
  { z: 17, symbol: 'Cl', name: 'Chlore' },
  { z: 18, symbol: 'Ar', name: 'Argon' },
  { z: 19, symbol: 'K', name: 'Potassium' },
  { z: 20, symbol: 'Ca', name: 'Calcium' },
  { z: 21, symbol: 'Sc', name: 'Scandium' },
  { z: 22, symbol: 'Ti', name: 'Titane' },
  { z: 23, symbol: 'Cr', name: 'Chrome' },
  { z: 24, symbol: 'Mn', name: 'Manganèse' },
  { z: 25, symbol: 'Fe', name: 'Fer' },
  { z: 26, symbol: 'Co', name: 'Cobalt' },
  { z: 27, symbol: 'Ni', name: 'Nickel' },
  { z: 28, symbol: 'Cu', name: 'Cuivre' },
  { z: 29, symbol: 'Zn', name: 'Zinc' },
  { z: 30, symbol: 'Ga', name: 'Gallium' },
  { z: 31, symbol: 'Ge', name: 'Germanium' },
  { z: 32, symbol: 'As', name: 'Arsenic' },
  { z: 33, symbol: 'Se', name: 'Sélénium' },
  { z: 34, symbol: 'Br', name: 'Brome' },
  { z: 36, symbol: 'Kr', name: 'Krypton' },
  { z: 37, symbol: 'Rb', name: 'Rubidium' },
  { z: 38, symbol: 'Sr', name: 'Strontium' },
  { z: 40, symbol: 'Zr', name: 'Zirconium' },
  { z: 42, symbol: 'Mo', name: 'Molybdène' },
  { z: 45, symbol: 'Rh', name: 'Rhodium' },
  { z: 46, symbol: 'Pd', name: 'Palladium' },
  { z: 47, symbol: 'Ag', name: 'Argent' },
  { z: 48, symbol: 'Cd', name: 'Cadmium' },
  { z: 50, symbol: 'Sn', name: 'Étain' },
  { z: 51, symbol: 'Sb', name: 'Antimoine' },
  { z: 52, symbol: 'Te', name: 'Tellure' },
  { z: 53, symbol: 'I', name: 'Iode' },
  { z: 54, symbol: 'Xe', name: 'Xénon' },
  { z: 55, symbol: 'Cs', name: 'Césium' },
  { z: 56, symbol: 'Ba', name: 'Baryum' },
  { z: 74, symbol: 'W', name: 'Tungstène' },
  { z: 78, symbol: 'Pt', name: 'Platine' },
  { z: 79, symbol: 'Au', name: 'Or' },
  { z: 80, symbol: 'Hg', name: 'Mercure' },
  { z: 81, symbol: 'Tl', name: 'Thallium' },
  { z: 82, symbol: 'Pb', name: 'Plomb' },
  { z: 83, symbol: 'Bi', name: 'Bismuth' },
  { z: 84, symbol: 'Po', name: 'Polonium' },
  { z: 86, symbol: 'Rn', name: 'Radon' },
  { z: 87, symbol: 'Fr', name: 'Francium' },
  { z: 88, symbol: 'Ra', name: 'Radium' },
  { z: 92, symbol: 'U', name: 'Uranium' },
];

export const IONS = [
  { name: 'Hydroxyde', formula: 'OH^-' },
  { name: 'Nitrite', formula: 'NO2^-' },
  { name: 'Nitrate', formula: 'NO3^-' },
  { name: 'Hypochlorite', formula: 'ClO^-' },
  { name: 'Chlorite', formula: 'ClO2^-' },
  { name: 'Chlorate', formula: 'ClO3^-' },
  { name: 'Perchlorate', formula: 'ClO4^-' },
  { name: 'Iodate', formula: 'IO3^-' },
  { name: 'Permanganate', formula: 'MnO4^-' },
  { name: 'Cyanure', formula: 'CN^-' },
  { name: 'Sulfite', formula: 'SO3^2-' },
  { name: 'Sulfate', formula: 'SO4^2-' },
  { name: 'Thiosulfate', formula: 'S2O3^2-' },
  { name: 'Hydrogénosulfate', formula: 'HSO4^-' },
  { name: 'Carbonate', formula: 'CO3^2-' },
  { name: 'Chromate', formula: 'CrO4^2-' },
  { name: 'Dichromate', formula: 'Cr2O7^2-' },
  { name: 'Phosphate', formula: 'PO4^3-' },
  { name: 'Arséniate', formula: 'AsO4^3-' },
  { name: 'Ammonium', formula: 'NH4^+' },
];

export const COMMENTS = {
  correct: [
    'Nickel chrome ! 😎',
    'Bien vu, l\'artiste ! 🎨',
    'Ça roule ma poule ! 🐔',
    'Bingo ! 🎯',
    'Impec ! ✨',
    'Tu assures ! 💪',
    'Tip top ! 🌟',
    'Ça, c\'est du propre ! 🧼',
    'Dans le mille ! 🏹',
    'Alors là, chapeau ! 🎩',
    'Fastoche ! 😎',
    'Au poil ! 👌',
    'Ça gaze ! 💨',
    'À l\'aise, Blaise ! 😎',
    'Cool Raoul ! 😎',
    'Tranquille, Émile ! 👌',
    'Impec de chez impec ! ✨',
    'Mazette, bien joué ! 😄',
    'La classe à Dallas ! 😎',
    'Ça baigne ! 👍',

  ],
  wrong: [
    'Aïe, raté ! 😅',
    'Y\'a comme un os… 🦴',
    'Oups, ça coince ! 🔧',
    'Pas de bol ! 🎳',
    'C\'est pas encore ça ! 🙈',
    'Allez, on se refait ! 🔄',
    'Ça craint un max ! 😬',
    'Raté pour celle-là ! 😅',
    'Y\'a encore du boulot ! 🛠️',
    'Bon… on fera mieux à la suivante ! 🤞',
    'Pas glop, pas glop ! 😅',
    'Ouh là, y\'a un hic ! 🤔',
    'C\'est ballot ! 😄',
    'Là, ça gaze moins… 😅',
    'Bon, celle-là nous a eus ! 😜',
    'On ne va pas en faire un fromage ! 🧀',
    'Ça ira mieux à la prochaine ! 👍',
    'Aïe… ça partait pourtant bien ! 😅',

  ],
  final0to3: [
    'Aïe aïe aïe… ça craint du boudin ! 😅 Allez, on se ressaisit et on remet les gaz ! 💪',
    'Ouh là… c\'est la Bérézina ! 😬 Mais c\'est pas une raison pour baisser les bras ! ✊',
    'Y\'a comme un os, là… 😄 Allez, on s\'accroche, c\'est pas gagné mais on y croit ! 🙌',
    'Bon… c\'est pas franchement Byzance ! 😅 On retrousse les manches et on remet ça !',
    'Pas glop, pas glop ! 😬 Mais on ne va pas en faire un fromage : prochain tour, on assure !',
    'Ouh là, y\'a du pain sur la planche ! 😄 Allez, on remet les gaz !',
    'Là, ça gaze pas des masses ! 😅 Allez, en voiture Simone, on recommence !',

  ],
  final4to5: [
    'Pas mal, pas mal ! C\'est pas encore le Pérou, mais y\'a du mieux ! 😎👍',
    'Y\'a de l\'idée ! 👍 Encore un petit effort et ça va commencer à avoir de la gueule ! 🎉',
    'On tient le bon bout ! 😄 Encore un peu et ça roule ma poule ! 🐔',
    'Ça commence à le faire ! 😎 Encore un chouïa et ça va rouler tout seul !',
    'C\'est pas Byzance, mais franchement, ça tient la route ! 👍',
    'Ça vient, ça vient ! 😄 Encore un petit coup de collier et c\'est dans la poche !',
    'Bon, ça gaze déjà mieux ! 😎 Encore un petit effort et ça roule ma poule !',

  ],
  final6to7: [
    'Alors là, tu assures ! 👍 Encore un petit effort et c\'est le top du top ! 🏆',
    'Nickel chrome ! 😎 Tu te débrouilles comme une chef ! 👩‍🍳',
    'Ça commence à décoiffer ! 🤩 Continue comme ça, t\'es sur la bonne voie ! 🚀',
    'Eh ben voilà, ça gaze ! 😎 Là, on commence à causer sérieusement !',
    'Au poil ! 👌 Ça commence à sentir le carton plein !',
    'Mazette ! 😄 C\'est du bon boulot, ça !',
    'À l\'aise, Blaise ! 😎 Encore un petit effort et c\'est du tout bon !',
    'Cool Raoul ! 😎 Ça commence à sacrément bien rouler !',

  ],
  final8to9: [
    'Waouh, ça décoiffe ! 🤩 Tu assures un max, ma parole ! 🎆',
    'Alors là, respect ! 😎 Tu te débrouilles comme une bête en chimie ! 🧪',
    'Ça, c\'est du lourd ! 💥 Encore un chouïa et c\'est le carton plein ! 🎯',
    'Alors là, c\'est la classe à Dallas ! 😎 Il ne manque vraiment pas grand-chose !',
    'Ça baigne ! 🌊 Encore un chouïa et c\'est le sans-faute !',
    'Mazette, tu assures un max ! 🤩 Le tableau périodique n\'a qu\'à bien se tenir !',
    'Alors là, ça gaze à fond ! 💨🧪 Encore un petit rien et c\'est le carton plein !',
    'À l\'aise, Blaise ! 😎 Là, franchement, ça devient du sérieux !',
    'Nickel chrome ! 😎 On frôle le sans-faute !',

  ],
  final10: [
    'Alors là… CHAPEAU ! 🏆 C\'est géant ! Tu les as tous atomisés ! 💥🧪',
    'Nickel chrome de chez nickel chrome ! 🏆 Là, tu assures un max ! 👑',
    'Le carton plein ! 🎉 Méga top ! La chimie n\'a plus de secrets pour toi ! 🧪',
    'Et voilà le carton plein ! 🎉 C\'est la classe à Dallas ! 😎🏆',
    'Alors là, c\'est nickel chrome ! 😎 Sans faute, la classe intégrale ! 🏆',
    'Mazette ! 🤩 10 sur 10 ! Là, y\'a rien à dire : chapeau l\'artiste ! 🎩',
    'Impec de chez impec ! 🏆 Pas une seule gamelle, tu assures un max !',
    'Et toc ! 💥 Carton plein ! Ça, c\'est du travail au poil ! 👌',
    'Ça gaze, ça pétille, c\'est nickel chrome ! 🧪🏆',
    'À l\'aise, Blaise ! 😎 10 sur 10, tranquille Émile ! 🏆',

  ],
};

/** Series proposees a l'ecran de depart. */
export const TOPICS = [
  { id: 'elements', label: 'Elements chimiques' },
  { id: 'ions', label: 'Ions polyatomiques' },
];

/** Nombre de questions par serie. */
export const QUESTIONS_PER_SERIES = 10;
